"""add webhook idempotency and payment references

Revision ID: 0274b7f0531a
Revises: b6660272c2ec
Create Date: 2026-09-05 21:00:07.874650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0274b7f0531a'
down_revision: Union[str, Sequence[str], None] = 'b6660272c2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.add_column('recovery_actions', sa.Column('external_reference', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_recovery_actions_external_reference'), 'recovery_actions', ['external_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_external_reference'), table_name='recovery_actions')
    op.drop_column('recovery_actions', 'external_reference')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
