"""add recovery actions and outcomes

Revision ID: b6660272c2ec
Revises: 46f3bdfb9b3c
Create Date: 2026-09-05 16:46:56.866330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6660272c2ec'
down_revision: Union[str, Sequence[str], None] = '46f3bdfb9b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('expected_recovery_probability', sa.Float(), nullable=True),
    sa.Column('expected_value_paise', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_action_type'), 'recovery_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_recovery_actions_created_at'), 'recovery_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_actions_idempotency_key'), 'recovery_actions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_recovery_actions_status'), 'recovery_actions', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_actions_transaction_id'), 'recovery_actions', ['transaction_id'], unique=False)
    op.create_table('recovery_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recovery_action_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount_recovered_paise', sa.Integer(), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_action_id'], ['recovery_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_outcomes_external_reference'), 'recovery_outcomes', ['external_reference'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_recovery_action_id'), 'recovery_outcomes', ['recovery_action_id'], unique=True)
    op.create_index(op.f('ix_recovery_outcomes_status'), 'recovery_outcomes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_outcomes_status'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_recovery_action_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_external_reference'), table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    op.drop_index(op.f('ix_recovery_actions_transaction_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_status'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_idempotency_key'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_created_at'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_action_type'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    # ### end Alembic commands ###
